import {Platform, StyleSheet} from 'react-native';

export const createStyles = palette =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: palette.pageBackground,
    },
    topHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      paddingTop: Platform.OS === 'ios' ? 50 : 16,
      backgroundColor: palette.headerBackground,
      borderBottomWidth: 1,
      borderBottomColor: palette.headerBorder,
    },
    backButton: {
      minWidth: 44,
      height: 36,
      borderRadius: 18,
      paddingHorizontal: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.navigationActiveBackground,
      marginRight: 12,
    },
    backButtonText: {
      marginLeft: 4,
      fontSize: 14,
      fontWeight: '600',
      color: palette.navigationActiveIcon,
    },
    topAvatar: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: palette.buttonBackground,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 16,
    },
    topTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      color: palette.headerText,
    },
    topSubtitle: {
      fontSize: 14,
      color: palette.textMuted,
      marginTop: 4,
    },
    fixedInfo: {
      backgroundColor: palette.cardBackground,
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: palette.headerBorder,
    },
    statusBox: {
      alignSelf: 'center',
      paddingHorizontal: 24,
      paddingVertical: 10,
      borderRadius: 30,
      borderWidth: 1.5,
      marginBottom: 16,
      backgroundColor: palette.chipSelectedBackground,
    },
    statusText: {
      fontSize: 17,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    datesRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    dateBlock: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 10,
      backgroundColor: palette.sectionBackground,
      borderRadius: 10,
      marginHorizontal: 6,
    },
    dateLabel: {
      fontSize: 12,
      color: palette.textMuted,
      marginBottom: 4,
    },
    dateValue: {
      fontSize: 16,
      fontWeight: '700',
      color: palette.headerText,
    },
    tabs: {
      flexDirection: 'row',
      backgroundColor: palette.navigationBackground,
      borderBottomWidth: 1,
      borderBottomColor: palette.navigationBorder,
    },
    tabItem: {
      flex: 1,
      paddingVertical: 16,
      alignItems: 'center',
    },
    tabActive: {
      borderBottomWidth: 3,
      borderBottomColor: palette.navigationActiveBorder,
    },
    tabLabel: {
      fontSize: 15,
      fontWeight: '600',
      color: palette.navigationText,
    },
    tabLabelActive: {
      color: palette.navigationActiveText,
      fontWeight: '700',
    },
    tabScroll: {
      flex: 1,
    },
    section: {
      backgroundColor: palette.cardBackground,
      borderRadius: 12,
      padding: 16,
      elevation: 1,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: palette.textPrimary,
      marginBottom: 16,
    },
    centerContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 60,
    },
    loadingText: {
      marginTop: 16,
      color: palette.loadingText,
      fontSize: 15,
    },
    emptyText: {
      marginTop: 16,
      color: palette.textDisabled,
      fontSize: 15,
    },
    errorText: {
      color: palette.textDanger,
      textAlign: 'center',
      padding: 24,
    },
    htmlWrapper: {
      backgroundColor: palette.cardBackground,
    },
    fixedSignButtonContainer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: palette.cardBackground,
      padding: 16,
      paddingBottom: Platform.OS === 'ios' ? 34 : 16,
      borderTopWidth: 1,
      borderTopColor: palette.headerBorder,
    },
    signButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.buttonBackground,
      paddingVertical: 16,
      borderRadius: 12,
    },
    signButtonText: {
      color: palette.buttonText,
      fontSize: 16,
      fontWeight: '700',
      marginLeft: 12,
    },
    subscriberCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.listItemBackground,
      padding: 12,
      borderRadius: 10,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: palette.listItemBorder,
    },
    subscriberAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: palette.buttonBackground,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    subscriberName: {
      fontSize: 16,
      fontWeight: '600',
      color: palette.listItemText,
    },
    subscriberRole: {
      fontSize: 13,
      color: palette.listItemSubtitleText,
    },
    addForm: {
      marginTop: 24,
      backgroundColor: palette.sectionBackground,
      padding: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.sectionBorder,
    },
    addTitle: {
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 16,
      color: palette.textPrimary,
    },
    selectField: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.selectBackground,
      borderWidth: 1,
      borderColor: palette.selectBorder,
      borderRadius: 10,
      padding: 14,
      marginBottom: 16,
    },
    label: {
      fontSize: 14,
      color: palette.textMuted,
      marginBottom: 8,
      fontWeight: '500',
    },
    roleRow: {
      flexDirection: 'row',
      gap: 12,
    },
    roleBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 10,
      backgroundColor: palette.chipBackground,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: palette.chipBorder,
    },
    roleBtnActive: {
      backgroundColor: palette.chipSelectedBackground,
      borderColor: palette.navigationActiveBorder,
    },
    roleText: {
      fontWeight: '600',
      color: palette.chipText,
    },
    addButton: {
      backgroundColor: palette.buttonBackground,
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: 'center',
    },
    addButtonDisabled: {
      backgroundColor: palette.buttonDisabledBackground,
    },
    addButtonText: {
      color: palette.buttonText,
      fontWeight: '700',
      fontSize: 15,
    },
    modalContent: {
      padding: 20,
      backgroundColor: palette.modalBackground,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    modalTitle: {
      fontSize: 19,
      fontWeight: '700',
      color: palette.modalHeaderText,
    },
    personRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: palette.selectOptionBorder,
    },
    personRowSelected: {
      backgroundColor: palette.listItemSelectedBackground,
    },
    personName: {
      fontSize: 16,
      color: palette.listItemText,
      flex: 1,
    },
    topSkeleton: {
      height: 100,
      backgroundColor: palette.loadingBorder,
      margin: 16,
      borderRadius: 12,
    },
    infoSkeleton: {
      height: 140,
      backgroundColor: palette.loadingBorder,
      marginHorizontal: 16,
      marginBottom: 8,
      borderRadius: 12,
    },
    tabsSkeleton: {
      height: 56,
      backgroundColor: palette.loadingBorder,
      marginHorizontal: 16,
      borderRadius: 12,
    },
  });
