import {StyleSheet} from 'react-native';

export const createStyles = palette =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: palette.pageBackground,
    },
    subHeader: {
      paddingHorizontal: 16,
      paddingTop: 9,
      paddingBottom: 9,
      backgroundColor: palette.headerBackground,
      borderBottomWidth: 1,
      borderBottomColor: palette.headerBorder,
    },
    searchRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    statusFilterSection: {
      marginTop: 10,
    },
    statusFilterLabel: {
      fontSize: 12,
      color: palette.textMuted,
      fontWeight: '600',
      marginBottom: 8,
    },
    statusFilterRow: {
      paddingRight: 4,
    },
    statusFilterChip: {
      borderWidth: 1,
      borderColor: palette.chipBorder,
      backgroundColor: palette.chipBackground,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 7,
      marginRight: 8,
    },
    statusFilterChipActive: {
      borderColor: palette.chipSelectedBorder,
      backgroundColor: palette.chipSelectedBackground,
    },
    statusFilterChipText: {
      fontSize: 12,
      color: palette.chipText,
      fontWeight: '600',
    },
    statusFilterChipTextActive: {
      color: palette.chipSelectedText,
    },
    searchInputContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.inputBackground,
      borderRadius: 8,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: palette.inputBorder,
      height: 40,
    },
    searchInput: {
      flex: 1,
      height: '100%',
      paddingHorizontal: 8,
      color: palette.inputText,
      fontSize: 14,
    },
    clearSearchButton: {
      padding: 4,
    },
    addButton: {
      backgroundColor: palette.buttonBackground,
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 12,
      shadowColor: palette.buttonShadow,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 3,
    },
    scrollContent: {
      padding: 16,
      paddingBottom: 32,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: 80,
    },
    skeletonCard: {
      backgroundColor: palette.loadingBackground,
      borderRadius: 16,
      padding: 16,
      marginBottom: 12,
    },
    skeletonLine: {
      backgroundColor: palette.loadingBorder,
      borderRadius: 6,
    },
    contractCard: {
      backgroundColor: palette.cardBackground,
      marginBottom: 12,
      borderRadius: 16,
      padding: 16,
      shadowColor: palette.cardShadow,
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
    },
    contractHeader: {
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: palette.dividerBorder,
    },
    headerContent: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    contractTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: palette.cardHeaderText,
      flex: 1,
      marginRight: 12,
    },
    statusBadge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
    },
    statusText: {
      fontSize: 12,
      fontWeight: '600',
      color: palette.badgeText,
      textTransform: 'uppercase',
    },
    contractBody: {
      padding: 16,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    infoLabel: {
      fontSize: 14,
      color: palette.textMuted,
      marginLeft: 8,
      marginRight: 8,
    },
    infoValue: {
      fontSize: 14,
      fontWeight: '500',
      color: palette.cardText,
      flex: 1,
    },
    dateContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    dateItem: {
      flex: 1,
      alignItems: 'center',
      padding: 12,
      backgroundColor: palette.sectionBackground,
      borderRadius: 8,
      marginHorizontal: 4,
    },
    dateLabel: {
      fontSize: 12,
      color: palette.textMuted,
      marginTop: 4,
      marginBottom: 2,
    },
    dateValue: {
      fontSize: 14,
      fontWeight: '600',
      color: palette.cardText,
    },
    viewButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.buttonBackground,
      margin: 16,
      marginTop: 0,
      paddingVertical: 12,
      borderRadius: 12,
    },
    viewButtonText: {
      color: palette.buttonText,
      fontSize: 16,
      fontWeight: '600',
      marginRight: 8,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: palette.headerText,
      marginBottom: 6,
      textAlign: 'center',
    },
    emptySubtitle: {
      fontSize: 14,
      color: palette.textDisabled,
      textAlign: 'center',
    },
  });
