import {StyleSheet} from 'react-native';

export const createStyles = palette =>
  StyleSheet.create({
    modalContainer: {
      backgroundColor: palette.modalBackground,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: '90%',
      width: '100%',
      shadowColor: palette.modalShadow,
      shadowOffset: {width: 0, height: -4},
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 10,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingVertical: 20,
      borderBottomWidth: 1,
      borderBottomColor: palette.modalBorder,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: palette.modalHeaderText,
    },
    headerCloseButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: palette.buttonBackgroundSecondary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalBody: {
      padding: 24,
    },
    inputGroup: {
      marginBottom: 20,
    },
    inputLabel: {
      fontSize: 16,
      fontWeight: '600',
      color: palette.textPrimary,
      marginBottom: 8,
    },
    required: {
      color: palette.textDanger,
    },
    selectInput: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: palette.selectBorder,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: palette.selectBackground,
    },
    selectInputContent: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    selectInputText: {
      fontSize: 16,
      flex: 1,
      color: palette.selectText,
    },
    placeholderText: {
      color: palette.selectPlaceholderText,
    },
    dateContainer: {
      flexDirection: 'row',
    },
    selectInputDate: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: palette.selectBorder,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 12,
      backgroundColor: palette.selectBackground,
      marginRight: 8,
    },
    yearInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: palette.inputBorder,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 12,
      fontSize: 16,
      color: palette.inputText,
      backgroundColor: palette.inputBackground,
      textAlign: 'center',
    },
    infoCard: {
      flexDirection: 'row',
      padding: 14,
      borderRadius: 14,
      backgroundColor: palette.surface,
      borderWidth: 1,
      borderColor: palette.sectionBorder,
    },
    infoIcon: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.cardBackground,
      marginRight: 12,
    },
    infoTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: palette.textPrimary,
    },
    infoText: {
      marginTop: 4,
      fontSize: 13,
      lineHeight: 18,
      color: palette.textMuted,
    },
    modalFooter: {
      flexDirection: 'row',
      padding: 20,
      borderTopWidth: 1,
      borderTopColor: palette.modalBorder,
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.buttonBorderSecondary,
      backgroundColor: palette.buttonBorderSecondary,
      alignItems: 'center',
      marginRight: 6,
    },
    cancelButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: palette.buttonTextSecondary,
    },
    createButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      backgroundColor: palette.buttonBackground,
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 6,
    },
    createButtonDisabled: {
      backgroundColor: palette.buttonDisabledBackground,
    },
    createButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: palette.buttonText,
    },
    pickerModalOverlay: {
      flex: 1,
      backgroundColor: palette.modalOverlay,
      justifyContent: 'flex-end',
    },
    pickerModalContent: {
      backgroundColor: palette.sheetBackground,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      width: '100%',
      maxHeight: '55%',
      elevation: 10,
    },
    pickerModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: palette.modalBorder,
    },
    pickerModalTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: palette.modalHeaderText,
    },
    pickerModalBody: {
      maxHeight: '100%',
    },
    selectOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 16,
      backgroundColor: palette.selectOptionBackground,
      borderBottomWidth: 1,
      borderBottomColor: palette.selectOptionBorder,
    },
    selectOptionActive: {
      backgroundColor: palette.selectOptionSelectedBackground,
    },
    selectOptionTextActive: {
      color: palette.selectOptionSelectedText,
      fontWeight: '600',
    },
    optionInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    iconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: palette.selectOptionSelectedBackground,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    optionName: {
      fontSize: 16,
      color: palette.modalText,
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: 40,
    },
    emptyText: {
      fontSize: 16,
      color: palette.textDisabled,
      marginTop: 12,
    },
    loadingContainer: {
      alignItems: 'center',
      paddingVertical: 40,
    },
    loadingText: {
      fontSize: 16,
      color: palette.loadingText,
      marginTop: 12,
    },
  });
